add basic helmfile capabilities

diff --git a/assets/out b/assets/out
--- a/assets/out
+++ b/assets/out
@@ -47,14 +47,20 @@ check_is_ready=$(jq -r '.params.check_is_ready // "false"' < $payload)
 kubeconfig_namespace=$(jq -r '.source.kubeconfig_namespace // "false"' < $payload)
 
 # helmfile params
+dir=$(jq -r '.params.dir // ""' < $payload)
 helmfile=$(jq -r '.params.helmfile // ""' < $payload)
 environment=$(jq -r '.params.environment // ""' < $payload)
-stat_values_file=$(jq -r '.params.state_values_file // ""' < $payload)
+state_values_file=$(jq -r '.params.state_values_file // ""' < $payload)
+state_values_set=$(jq -r '.params.state_values_set // ""' < $payload)
+selector=$(jq -r '.params.selector // ""' < $payload)
+env_vars=$(jq -r '.params.env_vars // ""' < $payload)
 
 if [ -z "$chart" ]; then
-  if [[ "$test" == "false" && "$delete" == "false" ]]; then
-    echo "invalid payload (missing chart)"
-    exit 1
+  if [ -z "$helmfile" ]; then
+    if [[ "$test" == "false" && "$delete" == "false" ]]; then
+      echo "invalid payload (missing chart)"
+      exit 1
+    fi
   fi
 fi
 
@@ -283,12 +289,15 @@ wait_ready_notice() {
   fi
 }
 
-helmfile_apply() {}
-helmfile_delete() {}
-helmfile_destroy() {}
+# helmfile_delete() {}
+# helmfile_destroy() {}
 
 helmfile_apply() {
-  apply_args=("apply" "--file" "$helmfile" "--suppress-secrets")
+  apply_args=()
+  if [ -n "$helmfile" ]; then
+    apply_args+=("--file" "$helmfile")
+  fi
+
   if [ -n "$environment" ]; then
     apply_args+=("--environment" "$environment")
   fi
@@ -297,10 +306,34 @@ helmfile_apply() {
     apply_args+=("--namespace" "$namespace")
   fi
 
+  if [ -n "$state_values_file" ]; then
+    apply_args+=("--state-values-file" "$state_values_file")
+  fi
+
+  if [ -n "$state_values_set" ]; then
+    apply_args+=("--state-values-set" "$state_values_set")
+  fi
+
+  if [ -n "$selector" ]; then
+    apply_args+=("--selector" "$selector")
+  fi
+  
+  apply_args+=("apply" "--suppress-secrets")
+
   if [ -n "$values" ]; then
     apply_args+=("--values" "$values")
   fi
 
+  if [ -n "$env_vars" ]; then
+    IFS=' ' read -r -a envvars <<< "${env_vars}"
+    export "${envvars[@]}"
+  fi
+
+  set -x
+  pwd
+  if [ -n "$dir" ]; then
+    cd /tmp/build/put/$dir
+  fi
   helmfile "${apply_args[@]}" | tee $logfile
 }
 
